[build]
  publish = "public"
  command = "echo 'No build needed'"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/draft"
  to = "/draft.html"
  status = 200
